name: Lint Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint-build:
    name: Build and Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js from nvmrc
        uses: actions/setup-node@4
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run build-compat
